### ISSUE TITLE
Build with Plugin Fails

### ISSUE THREAD

**Issue by dariusjulian** [Estimote/Unity3D-Indoor-Example#1]
I’m trying to run the Unity plugin and it keeps throwing errors.

For some reason it won’t let me build for Android with the included Gradle file.

>  \Documents\Adcetera Work\AR Service Line Demo\unity-plugin-master\example\Temp\gradleOut\build.gradle' line: 26
> 
> * What went wrong:
> A problem occurred evaluating root project 'gradleOut'.
> > Could not find method implementation() for arguments [{name=androidwrapper, ext=aar}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3s
> ]
> stdout[
> Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
> NDK is missing a "platforms" directory.
> If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Users\djportilla\AppData\Local\Android\sdk\ndk-bundle.
> If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
> 
> ]
> exit code: 1
> UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
> UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
> UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1 progress, System.String error)
> UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1 progress)
> Rethrow as GradleInvokationException: Gradle build failed
> UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1 progress)
> UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
> UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

If I build for Android Internal it throws an error in the logcat:

> Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.estimote.cloud_plugin.common.EstimoteCloudCredentials

____________________________

I’m looking through the Estimote- Unity plugin provided via Git and I don’t see any .jar or .aar files.  Shouldn’t there be one of those?  I’m a bit confused.

Any help would be appreciated as I’ve been pulling my hair out the last few hours trying to figure out the problem.

I'm running Unity 2018.2.1f1 on Windows 10.
I've tried several java jres.
Using Android Studio with API 28 and 8.1 (Oreo)

**Comment by heypiotr** [comment]
>Could not find method implementation()

This suggests you're using some old Gradle version, since `implementation` was only added in Gradle 3.4. Can you try updating to the latest version of Unity?

Also see this commit: 7605886cdb1c70472b0bfa2ac8ad0d3b96536c92

I updated the project to Unity 2018.2.13f1 (which I see uses Gradle 4.2), and made it use Android Gradle plugin 3.0.1 (https://github.com/Estimote/Unity3D-Indoor-Example/commit/7605886cdb1c70472b0bfa2ac8ad0d3b96536c92#diff-181f444fcfdf2adfc1b07e1bcb9e6496R8). The example project once again builds for me for Android on the latest version of Unity.

And since I was already updating stuff, also to the latest version of the Android Indoor SDK 🙂  (https://github.com/Estimote/Unity3D-Indoor-Example/commit/7605886cdb1c70472b0bfa2ac8ad0d3b96536c92#diff-181f444fcfdf2adfc1b07e1bcb9e6496R26)

**Comment by heypiotr** [comment]
>I’m looking through the Estimote- Unity plugin provided via Git and I don’t see any .jar or .aar files. Shouldn’t there be one of those? I’m a bit confused.

The Android Indoor SDK is pulled via a custom Gradle configuration:

https://github.com/Estimote/Unity3D-Indoor-Example/blob/master/Assets/Plugins/Android/mainTemplate.gradle#L26

See https://docs.unity3d.com/Manual/android-gradle-overview.html, "Providing a custom build.gradle template".

**Comment by dariusjulian** [comment]
Thank you so much for updating the files.  I was able to compile with the new plugin build.  Unfortunately when I build I'm getting an error in the Logcat:
 
> CloudManagerCallback failure: UnityEngine.AndroidJavaObject

I've updated Unity to the latest version and I'm still getting the same error.  
Any ideas?
Thank you again for your assistance.

**Comment by heypiotr** [comment]
Can you double-check your App ID, App Token, and location identifier?

I pushed a small update to make the error message more informative:

https://github.com/Estimote/Unity3D-Indoor-Example/commit/b709bc64e62d00f5a1f12e273c841f6c3ca22068

For example, if I use an incorrect location identifier, I'm now seeing this in `adb logcat`:

```
10-23 16:42:53.029 27382 27382 E Unity   : CloudManagerCallback failure, errorCode = -1, body = HTTP 404 Not Found
```

**Comment by dariusjulian** [comment]
Yes. It was the location identifier.  When I copied it from the Estimote Cloud site it added extra spaces between the hyphens.   Now I have it running and it isn't throwing an error but it remains on "Outside Location" even though I'm within my location area.  I'm pretty sure I have everything set up correctly with my location so I'm not sure what the issue could be.

**Comment by alazdu** [comment]
Hello. I'm trying to run the example without success.

I tried configuring the beacon as iBeacon and used the UUID as the <LOCATION IDENTIFIER>.
Did you make something special for the configuration of the beacon or in the estimote cloud?

Thanks

**Comment by Nima-Jamalian** [comment]
Hi,

Did you manage to figure out how to configure using iBeacon UUID. All I get is the "outside location" message.
